using System;
using HarmonyLib;
using ICities;
using UnityEngine;

namespace NaturalDisastersRenewal.Services.HarmonyPatches
{
    //This patch overrides the original behavior generated by the game using Harmony library, this nos called explicitly
    //in the code but harmony detected it and trigger it when this is needed
    [HarmonyPatch(typeof(DisasterHelpers))]
    [HarmonyPatch("DestroyNetSegments")]
    [HarmonyPatch(new Type[] { typeof(int), typeof(InstanceManager.Group), typeof(Vector3), typeof(float), typeof(float), typeof(float), typeof(float) })]

    class DestroyRoadsPatch
    {
        static bool Prefix(int seed, InstanceManager.Group group, Vector3 position, float totalRadius, float removeRadius, float destructionRadiusMin, float destructionRadiusMax)
        {
            DisasterType disasterType = DisasterHelpersModified.DisasterType;            

            if(!DisasterHelpersModified.EnableDestruction)
                return false;
            
            if (disasterType == DisasterType.Tornado && DisasterHelpersModified.DisasterIntensity <= DisasterHelpersModified.IntensityStartDestruction)
                return false;

            return true;
        }
    }
}